apiVersion: v1
kind: Service
metadata:
  name: greeting-ext-service
spec:
  selector:
    app: greet-client
  ports:
  - protocol: "TCP"
    port: 1000
    targetPort: 90
    nodePort: 30000
  type: NodePort